### ISSUE TITLE
2x Grid Align left, center, right

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/devtools#125]
### Summary

@mjabbink requested we add an option to left align, or center the grid. This sounds like it's helpful in situations in like Gatsby where the max-width is still applied, but the grid is left aligned. Probably need right aligned as well for RTL languages I would imagine.

Might be able to simply remove `margin-right`, or `margin-left` on `bx-dev--grid`. Only issue to keep in mind is the opposite influencer stops working when done this way. We can explore ways to keep them working, or find a new solution though if that's a deal breaker.

**Comment by photodow** [comment]
Planned for release 2.6.0!

![Oct-05-2021 12-54-08](https://user-images.githubusercontent.com/3793636/136076847-e8b3ecde-7c65-4e61-91ff-7188c5859c2c.gif)

**Comment by mjabbink** [comment]
nice work!

**Comment by mjabbink** [comment]
Boom!
