### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Lexecus** [carbon-design-system/devtools#164]
there is an issue in carbon devtools it don't wanna load.

**Comment by Lexecus** [comment]
and it says "Carbon not found"

**Comment by photodow** [comment]
Thanks for letting me know! Can you share anymore context to the issue you're having? What page are you looking at, and is carbon loaded on the page? What version of the tool?

**Comment by photodow** [comment]
Going to go ahead and close. Feel free to provide some additional information, and I'd be happy to take a closer look and re-open. Thanks again! 😄
