### ISSUE TITLE
Fix security warnings

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/devtools#17]
Dependabot is giving us some warnings after a scan, and we should take a moment to resolve these.

![image](https://user-images.githubusercontent.com/3793636/94835228-0ca62880-03d7-11eb-8a58-974f1d111f1b.png)

**Comment by anuragsati** [comment]
Hello! how can i start working on this?

**Comment by photodow** [comment]
@anuragsati hey! I haven't had a chance to look too in-depth at it, but it looks like the warnings are coming from some of our dependencies. I'm wondering if it's as simple as updating the dependencies in bringing these in, and refreshing the yarn cache?

![image](https://user-images.githubusercontent.com/3793636/94837788-53495200-03da-11eb-8d1b-b89e8c1cd806.png)

**Comment by anuragsati** [comment]
sorry i'm new, i can't figure out where and how to see these alerts.

**Comment by photodow** [comment]
All of the images are as detailed as I have to go on. It may be only viewable to the maintainer. If you don't have enough information don't stress. I appreciate you reaching out. The issue is pretty low it sounds like.

https://github.com/carbon-design-system/devtools/blob/master/yarn.lock

![image](https://user-images.githubusercontent.com/3793636/94840478-1717f080-03de-11eb-83c7-4331324ef744.png)
