### ISSUE TITLE
Not working on cloud.ibm.com

### ISSUE THREAD

**Issue by yung-christensen** [carbon-design-system/devtools#2]
Hey!

I was just checking out this amazing new tool you made. I am a Visual Designer on ZaaS Public Cloud Design Squad and I think this can help me a lot. Unfortunately it throws me an error "Carbon not found" when using it on cloud.ibm.com. I am on the latest Chrome on macOS 10.15

![image](https://user-images.githubusercontent.com/22619657/88672006-40b75180-d0e7-11ea-9237-16a850a31488.png)

Regards 
Jan

**Comment by photodow** [comment]
Hey, thanks for bringing this to my attention! Let me take a look. It's odd because it looks like the grid is overlayed and working, but it's just something odd going on with the pop up over there? Are y'all using custom prefixes?

**Comment by photodow** [comment]
I think https://github.com/carbon-design-system/devtools/commit/a9df0ec353c2ac92adb014f760010559af18721f fixes this issue. I just packaged it up and submitted it for review under version `2.1.0`. Looks like Firefox has already gone live. Chrome usually takes up to a day so keep and eye out for and report back if you get the update and still see the issue.

**Comment by photodow** [comment]
Looks like this got published overnight via Chrome. Let me know if you're still having problems with this.
