### ISSUE TITLE
Looking for maintainers! 👀 

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/devtools#252]
Do you find the Carbon DevTools helpful or integral to your workflow? Are you interested in working on an open source project? We'd love to bring on board another primary maintainer!

We're incredibly thankful for all the hard work @photodow has put in on this project over the past few years, and are interested in establishing another primary maintainer if there's interest from someone within the community.

The biggest challenges for the project at this time are the following:

- https://github.com/carbon-design-system/devtools/issues/158
- https://github.com/carbon-design-system/devtools/issues/84

The existing plugin does not work or detect Carbon on pages using Carbon v11. Additionally, without the update to Manifest v3, the existing plugin will [stop running in Chrome in January 2023](https://developer.chrome.com/blog/mv2-transition/).

If you're interested, please comment below. Thanks!

**Comment by motou** [comment]
Sure, I would like to contribute on this project to make the dev-tool be more valuable to the developers 🤗
