### ISSUE TITLE
Option to remove columns/gutters

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/devtools#3]
### Summary

> I would like a feature where I have the option to remove columns or gutters from visibility.

### Justification

> Removing items from viewpoint would allow to better focus on the specific gutters or columns that are requiring attention.

**Comment by photodow** [comment]
Thanks for sharing @ariellalgilmore. I'd love to flesh this out with you a little more. A couple of questions I have are what the interaction should look like, and how this might work responsively.

**Comment by photodow** [comment]
Implemented in v2.3.0.

To use hold down `Shift` `+` `~` to allow the grid to be interacted with. Then `click` whichever column you'd like to hide/show.


![Sep-08-2020 09-50-25](https://user-images.githubusercontent.com/3793636/92492247-c3d4c880-f1b8-11ea-8c8f-092f31b21d83.gif)
