### ISSUE TITLE
Update Firefox extension to consistently use `Carbon Devtools`

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/devtools#321]
This repo is titled `Carbon Devtools`. Same with the Chrome extension.

In the [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/carbondevtools), I'm seeing `Carbon DevTools` and in the description, `Carbon Dev-Tools`. Regardless if the name has the `(v10)` suffix or not, can we remove the `-` and use consistent capitalization `Carbon Devtools`?

**Comment by mattrosno** [comment]
FYI @andy-blum.

**Comment by motou** [comment]
The addon name is unified.
