### ISSUE TITLE
Automate dependency management

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/devtools#66]
Automation for managing dependency updates, similarly to https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/.github/workflows/update.yml

If there's an agreement, I'm happy to explore and contribute the changes to accommodate this.

**Comment by photodow** [comment]
This is great. I went ahead and leveraged dependabot for some of this since it took like 5 minutes for me to create its file, but if you and your team have a more efficient way of managing this with a github action please feel free explore. Thanks! :D
