### ISSUE TITLE
Migrate to manifest v3

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/devtools#84]
Here is more information on it: [chrome](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/) | [firefox](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/)

One of the biggest changes I'm seeing is service workers instead of background.js now, and the opportunity to move towards promise based apis instead of the callback method chrome had us using.

> **Chrome**
> Manifest V3 is available beginning with **Chrome 88**, and the Chrome Web Store begins accepting MV3 extensions in **January 2021**.

> **Firefox**
> As of this writing, we are hoping to complete enough work on this project to support developer testing in Q4 2021 and start accepting v3 submissions in **early 2022**.

Firefox could be a blocker here until next year.

**Comment by motou** [comment]
@erzhan-temir-mamyrov

would you like to take a look at it?
