### ISSUE TITLE
Lint code

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/devtools#9]
We've gone way too long without any proper code linting. We should try to align with Carbon on this.

- [x] [commitlint](https://github.com/carbon-design-system/carbon/blob/master/package.json#L73-L132)
- [x] [prettier](https://github.com/carbon-design-system/carbon/blob/master/prettier.config.js)
- [x] [eslint](https://github.com/carbon-design-system/carbon/blob/master/package.json#L133-L137)
- [x] [stylelint](https://github.com/carbon-design-system/carbon/blob/master/package.json#L138-L142)

**Comment by drawsoek** [comment]
I can help with this

**Comment by photodow** [comment]
Awesome! So I updated with 4 tasks to this based on what [Carbon](https://github.com/carbon-design-system/carbon) is doing to lint their code. The more we align the better, but feel free to pick one and submit a PR. Let me know if you have any trouble with anything that I might be able to help with. I can create separate tickets for each of these too. Thanks!
