### ISSUE TITLE
General page info

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/devtools#96]
When reviewing an adopter's production page, I often want to find out what version of Carbon for Dotcom they are on. Is it possible to get general page info, like release number of our lib, framework, last updated (might help to know if there’s a caching issue), and any geo / language or meta data the page has.

**Comment by photodow** [comment]
Just wanted to quickly put a couples draft notes down on this while it's fresh on my mind. Let me know what you think.

Most if not all of this information we can get from the `digitalData`. Not sure how well we can breakdown the libraries.

Using structured list, code snippet, tags, links, and we could create something like this. Organization could either live under an accordion item like the others, but that could be a bit much. Either we could add a secondary level of accordions, or maybe links under it that kind of flies over a new view with that section of information. 

![Sep-23-2021 11-58-07](https://user-images.githubusercontent.com/3793636/134551743-ed074591-054e-404a-b5bc-9b0b9489990f.gif)
